# Generated by Django 3.2.4 on 2021-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('transmission', models.SmallIntegerField(blank=True, choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default=1, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['manufacturer', 'model'],
            },
        ),
    ]
